// Mapeado 1:1 desde frontend/src/constants/api.ts de SkyVault Web V2.6

const BASE_URL = process.env.EXPO_PUBLIC_API_BASE_URL ?? 'http://localhost:8080/api/v1';
const WS_URL   = process.env.EXPO_PUBLIC_WS_URL   ?? 'http://localhost:8080/ws';

export { BASE_URL, WS_URL };

export const API = {
  AUTH: {
    LOGIN:    '/auth/login',
    REGISTER: '/auth/register',
    REFRESH:  '/auth/refresh',
    LOGOUT:   '/auth/logout',
    ME:       '/auth/me',
  },
  ME: {
    PROFILE:               '/me',
    UPDATE:                '/me',
    DELETE:                '/me',
    ACTIVITY:              '/me/activity',
    ACTIVITY_RECORD:       (id: number) => `/me/activity/${id}`,
    FAVORITES:             '/me/favorites',
    FAVORITE_ADD:          (id: number) => `/me/favorites/${id}`,
    FAVORITE_REMOVE:       (id: number) => `/me/favorites/${id}`,
    NOTIFICATIONS:         '/me/notifications',
    NOTIFICATIONS_UNREAD:  '/me/notifications/unread-count',
    NOTIFICATION_READ:     (id: string) => `/me/notifications/${id}/read`,
    NOTIFICATIONS_READ_ALL:'/me/notifications/read-all',
    NOTIFICATION_BY_ID:    (id: string) => `/me/notifications/${id}`,
  },
  AIRCRAFT: {
    LIST:     '/aircraft',
    DETAIL:   (identifier: string | number) => `/aircraft/${identifier}`,
    SEARCH:   '/aircraft/search',
    POPULAR:  '/aircraft/popular',
    FEATURED: '/aircraft/featured',
    SIMILAR:  (id: number) => `/aircraft/${id}/similar`,
    COMPARE:  '/aircraft/compare',
  },
  CATALOG: {
    ALL:                  '/catalogs/all',
    TYPES:                '/catalogs/types',
    TYPE_BY_ID:           (id: number) => `/catalogs/types/${id}`,
    PRODUCTION_STATES:    '/catalogs/production-states',
    PRODUCTION_STATE_BY_ID:(id: number) => `/catalogs/production-states/${id}`,
    SIZE_CATEGORIES:      '/catalogs/size-categories',
    SIZE_CATEGORY_BY_ID:  (id: number) => `/catalogs/size-categories/${id}`,
    DETERMINE_SIZE:       '/catalogs/size-categories/determine',
  },
  MANUFACTURERS: {
    LIST:       '/manufacturers',
    BY_ID:      (id: number) => `/manufacturers/${id}`,
    FAMILIES:   (id: number) => `/manufacturers/${id}/families`,
    AIRCRAFT:   (id: number) => `/manufacturers/${id}/aircraft`,
    SUMMARY:    '/manufacturers/summary',
    COUNTRIES:  '/manufacturers/countries',
    SEARCH:     '/manufacturers/search',
    STATISTICS: '/manufacturers/statistics',
  },
  FAMILIES: {
    LIST:       '/families',
    DETAIL:     (id: number) => `/families/${id}`,
    AIRCRAFT:   (id: number) => `/families/${id}/aircraft`,
    SUMMARY:    '/families/summary',
    CATEGORIES: '/families/categories',
    POPULAR:    '/families/popular',
    SEARCH:     '/families/search',
    STATISTICS: '/families/statistics',
  },
  SEARCH: {
    SUGGEST:  '/search/suggest',
    GLOBAL:   '/search/global',
    AIRCRAFT: '/search/aircraft',
    POPULAR_TERMS: '/search/popular-terms',
    ADVANCED: '/search/advanced',
  },
  UPDATES: {
    BASE:           '/updates',
    BY_ID:          (id: number) => `/updates/${id}`,
    APPROVE:        (id: number) => `/updates/${id}/approve`,
    REJECT:         (id: number) => `/updates/${id}/reject`,
    CATEGORIES:     '/update-categories',
    CATEGORY_BY_ID: (id: number) => `/update-categories/${id}`,
  },
  ADMIN: {
    USERS:          '/admin/users',
    USER_BY_ID:     (id: string | number) => `/admin/users/${id}`,
    USER_ROLE:      (id: string | number) => `/admin/users/${id}/role`,
    USER_ACTIVATE:  (id: string | number) => `/admin/users/${id}/activate`,
    USER_DEACTIVATE:(id: string | number) => `/admin/users/${id}/deactivate`,
    USER_DELETE:    (id: string | number) => `/admin/users/${id}`,
    STATS:          '/admin/stats',
    ACTIVITY:       '/admin/activity',
    AIRCRAFT:       '/aircraft',
    AIRCRAFT_ID:    (id: number) => `/aircraft/${id}`,
    // Cache — usar rutas canónicas del backend (no alias del web):
    CACHE_STATS:    '/admin/cache/statistics',
    CACHE_CLEAR:    '/admin/cache/operations',
    NOTIFICATIONS:  '/admin/notifications',
  },
  STATISTICS: {
    SYSTEM:        '/statistics/system',
    AIRCRAFT:      '/statistics/aircraft',
    MANUFACTURERS: '/statistics/manufacturers',
    FAMILIES:      '/statistics/families',
    SEARCH:        '/statistics/search',
    DISTRIBUTIONS: '/statistics/distributions',
    DISTRIBUTION_MANUFACTURERS: '/statistics/distributions/manufacturers',
    DISTRIBUTION_TYPES: '/statistics/distributions/types',
    DISTRIBUTION_PRODUCTION_STATES: '/statistics/distributions/production-states',
    DISTRIBUTION_SIZE_CATEGORIES: '/statistics/distributions/size-categories',
    DISTRIBUTION_INTRODUCTION_YEARS: '/statistics/distributions/introduction-years',
    POPULAR_AIRCRAFT: '/statistics/popular/aircraft',
    POPULAR_COMPARISONS: '/statistics/popular/comparisons',
    POPULAR:       '/statistics/popular',
    USAGE:         '/statistics/usage',
    CUSTOM:        '/statistics/custom',
  },
  HEALTH: {
    COMPLETE:  '/health/complete',
    LIVENESS:  '/health/liveness',
    READINESS: '/health/readiness',
  },
  METRICS: {
    ENDPOINTS: '/metrics/endpoints',
    BUSINESS:  '/metrics/business',
    REALTIME:  '/metrics/realtime',
  },
} as const;